//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DSI.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Employee
    {
        [Display(Name="ID Empleado")]
        public int EmployeeID { get; set; }

        [Display(Name="Nombres")]
        public string Name { get; set; }

        [Display(Name="Apellidos")]
        public string LastName { get; set; }

        [Display(Name="Dirección")]
        public string Address { get; set; }

        [Display(Name = "Salario")]
        public Nullable<decimal> Salary { get; set; }

        [Display(Name = "Celular")]
        public Nullable<decimal> Phone { get; set; }
    }
}
