//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class edicion
    {
        public int numero { get; set; }
        public string codUsuario { get; set; }
        public string codDoc { get; set; }
        public string tipoDoc { get; set; }
        public string modificacion { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public Nullable<System.TimeSpan> hora { get; set; }
    }
}
