//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Entities : DbContext
    {
        public Entities()
            : base("name=Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<detalleOC> detalleOC { get; set; }
        public virtual DbSet<edicion> edicion { get; set; }
        public virtual DbSet<factura> factura { get; set; }
        public virtual DbSet<OC> OC { get; set; }
        public virtual DbSet<OP> OP { get; set; }
        public virtual DbSet<usuario> usuario { get; set; }
    }
}
