//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SGL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OP
    {
        public string codOP { get; set; }
        public Nullable<System.DateTime> fecha { get; set; }
        public string unidad { get; set; }
        public string planta { get; set; }
        public string scop { get; set; }
        public string estacion { get; set; }
        public Nullable<int> galones { get; set; }
        public string octanaje { get; set; }
    }
}
